Add support in Commons CSV for tracking byte positions during parsing.
marklogic/commons-csv pull request #11
Opened 2024-11-13 23:21 UTC by DarrenJAN

Summary of Modifications

1. **Test Data Files**: Added new test data files, and updated pom.xml to exclude these files from RAT checks, avoiding unapproved license checks.
2. **CSVParser class**:
 Constructor Enhancements
a. Added support for an optional parameter -- **String encoding**--, which specifies the encoding to use for the reader.
4. **CSVRecord class**
- private long characterByte:  start byte position of this record 
Add new Constructor: support track byte positions in record class 
5. **ExtendedBufferedReader Class**:

- private long bytesRead: Tracks the number of bytes read so far.
- private long bytesReadMark: Stores the marked byte position.
- CharsetEncoder encoder: Encoder used to calculate byte size of characters.
- getCharBytes(int current): This function calculates character bytes based on UTF-8 encoding. Note: it only supports UTF-8 due to the encoding algorithm used. Full encoding can be supported and we just need more effort on this. 
- reset() and mark() Methods: Enhanced to prevent consuming characters and bytes unintentionally.

Test result:
mvn 
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/df0e8277-4a89-4aa0-b45a-c763eaa7e3e0">
<img width="1599" alt="image" src="https://github.com/user-attachments/assets/8fccade6-e530-4645-9a44-238fbcb8d826">
Pass unit tests and other restrictions

2024-11-14 02:02 UTC, yunzvanessa requested changes

2024-11-14 02:02 UTC, vzhang-progress commented on pom.xml
>    <url>https://commons.apache.org/proper/commons-csv/</url>
The version here on line 32 should be our corresponding version like 1.12.1-marklogic

2024-11-14 02:02 UTC, vzhang-progress commented on pom.xml
> + Modifications copyright © 2022, 2024 MarkLogic Corporation.
I believe Matt modified this file as well in 2017

2024-11-14 18:34 UTC, yunzvanessa approved these changes

2024-11-18 16:34 UTC, DarrenJAN commented
1. Needs to replace the jar and regression test before merge
2. Remember to squash and merge

2024-12-02 22:06 UTC, DarrenJAN commented
There is a functional bug in the mlcp that needs to be addressed

2024-12-02 22:07 UTC, merged