Apply Matt's fix to allow track byte position in 1.5.2-marklogic
marklogic/commons-csv pull request #6
Opened 2024-10-29 22:31 UTC by DarrenJAN

Please note that it is required to use Java 11 to build and run tests.

Here are summaries of the modifications:
1. Add our test data files to rat exclusions to avoid unapproved license checks in pom.xml
2. Add CSVParser constructor
3. Add CSVRecord constructor
    1. Remove mapping Since version 1.8, the mapping between the column header and the column index was removed from the serialized state (Note: Commons CSV: Latest version is 1.12.0)
4. Add other Parser helper functions
    1. ExtendedBufferedReader()
    2. getBytesRead()
    3. getCharacterByte() in CSVRecord class
5. Add new Junit test — src/test/java/org/apache/commons/csv/issues/JiraCsv196Test.java
   1. Update deprecated import package name (ie: import org.junit.Test; - > import org.junit.jupiter.api.Test; ; import org.junit.Assert →  import static org.junit.jupiter.api.Assertions.assertEquals; )
   2. new InputStreamReader object to get test input
6. Override the peek() functions in ExtendedBufferedReader class to avoid consuming the byte

2024-10-31 21:49 UTC, yunzvanessa requested changes
Hi Yuzhan,

The functionality looks good. Two things to focus on:
1. Please go over all the comments you added since we would like to formalize it and attempt for a PR against the central repo.
2. Please confirm the copyright info with Shawna and update them in the source files you are changing accordingly.

2024-10-31 21:49 UTC, yunzvanessa commented on src/main/java/org/apache/commons/csv/CSVFormat.java
> +     * @param reader the input stream
Please improve the comments to something that makes more sense.

2024-10-31 21:49 UTC, yunzvanessa commented on src/main/java/org/apache/commons/csv/CSVParser.java
> +    public CSVParser(final Reader reader, final CSVFormat format, final long characterOffset, final long recordNumber,
Please add comments here, you can follow the comments for other parsers.

2024-10-31 21:50 UTC, yunzvanessa commented
Can you also investigate the failing checks above and make sure they are okay?

2024-11-04 19:08 UTC, DarrenJAN commented
> Hi Yuzhan,
> 
> The functionality looks good. Two things to focus on:
> 
> 1. Please go over all the comments you added since we would like to formalize it and attempt for a PR against the central repo.
> 2. Please confirm the copyright info with Shawna and update them in the source files you are changing accordingly.

1. I updated some comments
2. Should I confirm the copyright right now or wait until creating PR for the upstream project?

2024-11-04 23:20 UTC, yunzvanessa commented on src/main/java/org/apache/commons/csv/CSVParser.java
> +     * @since 1.12
Please remove "since 1.12", since commons-csv will decide in which version it will be in

2024-11-04 23:21 UTC, yunzvanessa requested changes
Hi Yuzhan,

Just a minor detail for you to change. Thanks

2024-11-05 16:13 UTC, merged